STANDARD_USER = "standard_user"
STANDARD_PASSWORD = "secret_sauce"
LOCKED_OUT_USER = "invalid_user"
URL = "https://www.saucedemo.com"
INVENTORY_URL = "https://www.saucedemo.com/inventory.html"
LOW_TO_HIGH = "Price (low to high)"
HIGH_TO_LOW = "Price (high to low)"
PRODUCT_LANDING_PAGE_TITLE = "Products"
ERROR_LOGIN_FAILED = "Epic sadface: Username and password do not match any user in this service"
DEFAULT_WAIT = 10
SHORT_WAIT = 5
LONG_WAIT = 20
PRODUCT_TITLES = ["'Sauce Labs Backpack'", "'Sauce Labs Bike Light'"]
FIRST_NAME = "Chandler"
LAST_NAME = "Bing"
POSTAL_CODE = "90001"
ORDER_SUCCESS_MESSAGE = "Thank you for your order!"
PRODUCT_NAMES = ['Sauce Labs Backpack', 'Sauce Labs Bike Light']
ORDER_CONFIRMATION_PAGE_TITLE = "Checkout: Complete!"
